name: Release
on:
  release:
    types:
      - created

jobs:
  pre-release-steps:
    if: "github.event.release.prerelease"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main

      # Update the checked out pyproject.toml with the version number of the release
      - name: Sync pyproject.toml with release version
        id: sync_version
        run: |
          TAG_NAME=${{ github.ref }}
          VERSION=$(echo $TAG_NAME | sed 's/refs\/tags\/v//')
          RELEASE_VERSION=${VERSION/-pre/}  # Remove '-pre' from the version
          sed -i "s/^version = \".*\"/version = \"$RELEASE_VERSION\"/" pyproject.toml
          echo "::set-output name=release_version::$RELEASE_VERSION"

          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add pyproject.toml
          git commit -m "Pre-release: Sync version to pyproject.toml"
          git push

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "v${{ steps.sync_version.outputs.release_version }}"
          release_name: "Release v${{ steps.sync_version.outputs.release_version }}"
          draft: false
          prerelease: false

  build-and-release:
    needs: pre-release-steps
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main

      # Build deployer image to use for PyPI publishing
      - name: Build and push Docker image
        id: build
        run: docker build -t data-product-hub-deployer .
        env:
          DOCKER_BUILDKIT: 1

      # Create release and publish to PyPI only for non-prerelease releases
      - name: Publish to PyPI
        run: |
          docker run --rm \
            -e PYPI_USERNAME='__token__' \
            -e PYPI_PASSWORD_PROD='${{ secrets.PYPI_API_TOKEN }}' \
            -v $PWD:/app \
            data-product-hub-deployer make publish-prod
